package com.pondersource.shared.vocab

object VCARD {
    const val namespace = "http://www.w3.org/2006/vcard/ns#"

    const val Individual = "${namespace}Individual"
    const val AddressBook = "${namespace}AddressBook"
    const val Group = "${namespace}Group"
    const val Homepage = "${namespace}Homepage"
    const val WebId = "${namespace}WebId"
    const val PublicId = "${namespace}PublicId"
    const val Home = "${namespace}Home"
    const val Work = "${namespace}Work"
    const val nameEmailIndex = "${namespace}nameEmailIndex"
    const val groupIndex = "${namespace}groupIndex"
    const val includesGroup = "${namespace}includesGroup"
    const val inAddressBook = "${namespace}inAddressBook"
    const val member = "${namespace}member"
    const val fn = "${namespace}fn"
    const val hasUID = "${namespace}hasUID"
    const val hasName = "${namespace}hasName"
    const val familyName = "${namespace}family-name"
    const val givenName = "${namespace}given-name"
    const val additionalName = "${namespace}additional-name"
    const val honorificPrefix = "${namespace}honorific-prefix"
    const val honorificSuffix = "${namespace}honorific-suffix"
    const val hasPhoto = "${namespace}hasPhoto"
    const val hasRelated = "${namespace}hasRelated"
    const val url = "${namespace}url"
    const val hasAddress = "${namespace}hasAddress"
    const val bday = "${namespace}bday"
    const val anniverary = "${namespace}anniverary"
    const val hasEmail = "${namespace}hasEmail"
    const val hasTelephone = "${namespace}hasTelephone"
    const val organizationName = "${namespace}organization-name"
    const val role = "${namespace}role"
    const val title = "${namespace}title"
    const val note = "${namespace}note"
    const val value = "${namespace}value"
    const val hasMember = "${namespace}hasMember"
}