package com.pondersource.shared.vocab

object VCARD {
    const val NAMESPACE = "http://www.w3.org/2006/vcard/ns#"

    const val INDIVIDUAL = "${NAMESPACE}Individual"
    const val ADDRESS_BOOK = "${NAMESPACE}AddressBook"
    const val GROUP = "${NAMESPACE}Group"
    const val HOMEPAGE = "${NAMESPACE}Homepage"
    const val WEB_ID = "${NAMESPACE}WebId"
    const val PUBLIC_ID = "${NAMESPACE}PublicId"
    const val HOME = "${NAMESPACE}Home"
    const val WORK = "${NAMESPACE}Work"
    const val NAME_EMAIL_INDEX = "${NAMESPACE}nameEmailIndex"
    const val GROUP_INDEX = "${NAMESPACE}groupIndex"
    const val INCLUDES_GROUP = "${NAMESPACE}includesGroup"
    const val IN_ADDRESS_BOOK = "${NAMESPACE}inAddressBook"
    const val MEMBER = "${NAMESPACE}member"
    const val FN = "${NAMESPACE}fn"
    const val HAS_UID = "${NAMESPACE}hasUID"
    const val HAS_NAME = "${NAMESPACE}hasName"
    const val FAMILY_NAME = "${NAMESPACE}family-name"
    const val GIVEN_NAME = "${NAMESPACE}given-name"
    const val ADDITIONAL_NAME = "${NAMESPACE}additional-name"
    const val HONORIFIC_PREFIX = "${NAMESPACE}honorific-prefix"
    const val HONORIFIC_SUFFIX = "${NAMESPACE}honorific-suffix"
    const val HAS_PHOTO = "${NAMESPACE}hasPhoto"
    const val HAS_RELATED = "${NAMESPACE}hasRelated"
    const val URL = "${NAMESPACE}url"
    const val HAS_ADDRESS = "${NAMESPACE}hasAddress"
    const val BIRTHDAY = "${NAMESPACE}bday"
    const val ANNIVERSARY = "${NAMESPACE}anniversary"
    const val HAS_EMAIL = "${NAMESPACE}hasEmail"
    const val HAS_TELEPHONE = "${NAMESPACE}hasTelephone"
    const val ORGANIZATION_NAME = "${NAMESPACE}organization-name"
    const val ROLE = "${NAMESPACE}role"
    const val TITLE = "${NAMESPACE}title"
    const val NOTE = "${NAMESPACE}note"
    const val VALUE = "${NAMESPACE}value"
    const val HAS_MEMBER = "${NAMESPACE}hasMember"
}
